- name: Install Debian SSL certs 
  apt: pkg=ca-certificates state=present update_cache=yes 

- name: Install Packetbeat dependencies
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
        - libpcap0.8
  tags: deps

- name: Check if Packetbeat is already at the right version
  shell: dpkg -s packetbeat | grep Version | awk '{print $2}'
  register: installed_version
  always_run: True
  ignore_errors: True

- name: Download Packetbeat agent
  get_url: >
        url=https://github.com/packetbeat/packetbeat/releases/download/v{{ packetbeat.version }}/packetbeat_{{ packetbeat.version }}-1_{{ packetbeat.deb.arch }}.deb
        dest=/tmp/packetbeat_{{ packetbeat.version }}-1_{{ packetbeat.deb.arch }}.deb
  when: installed_version.stdout != '{{ packetbeat.version }}'

- name: Install Packetbeat agent
  apt: deb=/tmp/packetbeat_{{ packetbeat.version }}-1_{{ packetbeat.deb.arch }}.deb
  when: installed_version.stdout != '{{ packetbeat.version }}'
