logstash:
    version: 1.4

    config:
        heap_size: 64

        file_inputs:
            syslog:
                enabled: true
                path:
                        - "/var/log/syslog"
                        - "/var/log/messages"
            nginx_access:
                enabled: true
                path:
                        - "/var/log/nginx/access.log"
            nginx_error:
                enabled: true
                path:
                        - "/var/log/nginx/error.log"


# Find aggregator's IP address from the inventory vars
aggregator_bind_iface: "{{ hostvars[groups['aggregator'][0]].get('main_iface', 'eth0') }}"
aggregator_bind_ip: "{{ hostvars[groups['aggregator'][0]]['ansible_' + aggregator_bind_iface ].ipv4.address }}"
aggregator_redis_port: 6380

